MapUx\Command\InstallAssetsCommand:
  tags:
    - { name: 'console.command', command: 'mapux:install' }
MapUx\Command\UninstallAssetsCommand:
  tags:
    - { name: 'console.command', command: 'mapux:uninstall' }
